---
# Create an instance on NeCTAR
- name: Create an instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: '{{ item.volumes }}'
    auto_floating_ip: yes
    wait: yes
    network: qh2-uom-internal
    timeout: 600
    state: present
  loop: '{{ instances }}'
  register: os_instance

- debug:
    msg: "Instance {{ item.openstack.name }} has been created. IP address is {{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

- name: Wait for connection
  wait_for:
    host: "{{ item.openstack.public_v4 }}"
    port: 22
    timeout: 120
    search_regex: OpenSSH
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

# Add hosts to Ansible in-memory inventory
- name: Add host
  add_host:
    name: '{{ item.openstack.public_v4 }}'
    groups: COMP90024
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

# Add ip in the manager list
- name: Add the manager node
  add_host:
    name: '{{ item.openstack.public_v4 }}'
    groups: managers
  loop: '{{ [ os_instance.results[0] ] }}'
  when: item.openstack is defined

# Add ip in the worker list
- name: Add worker nodes
  add_host:
    name: '{{ item.openstack.public_v4 }}'
    groups: workers
  loop: '{{ os_instance.results | difference([os_instance.results[0]]) }}'
  when: item.openstack is defined
#  when: (item == '{{os_instance.results[0]}}' and item.openstack is defined) or item != '{{os_instance.results[0]}}'

