---
- name: Deploy stack from a compose file
  become: yes
  command: 'docker service create --replicas 2 --network="host" --publish mode=host, target=80, published=80 --name=myweb web-server'
  args:
    chdir: '/docker/'

#  docker_stack:
#    state: present
#    name: mystack
#    compose:
#      - "/docker/docker-compose.yaml"
#  register: output
#
#- debug:
#    msg: '{{ output }}'
