---
- name: Copying file to remote
  become: yes
  copy:
    src: "./files/docker-compose.yaml"
    dest: "/docker"

- name: Deploy stack from a compose file
  become: yes
  docker_stack:
    state: present
    name: mystack
    compose:
      - "/docker/docker-compose.yaml"
  register: output

- debug:
    msg: '{{ output }}'