---
- name: Copy compose file into react folder
  become: yes
  copy:
    src: './files/docker-compose.yaml'
    dest: '/docker/react/'

- name: Create react app
  become: yes
  args:
    chdir: '/docker/react'
  command: 'yarn create react-app {{ APP_NAME }}'

- name: Copy Dockerfile into react app
  become: yes
  copy:
    src: './files/Dockerfile'
    dest: '/docker/react/{{ APP_NAME }}'

- name: Build react image from Dockerfile
  become: yes
  docker_image:
    name: myreact:latest
    build:
      pull: yes
      path: "/docker/react/{{ APP_NAME }}"
    source: build